User activity chart data collecting
Zaczero/openstreetmap-ng pull request #65
Opened 2024-06-25 19:00 UTC by tomekrzymyszkiewicz

This PR adds `activity` key to the user controller response, which stores values from 0 to 19 classifying activity of the user in the past 365 days. This data will be the source of truth to create an activity graph described in issue #47. I'm pushing only this part of the code, as I still don't feel comfortable with JS and don't want to stay stacked there.

The count_per_day_by_user_id method returns dict, where each key (datetime) have value (int) of count on ChangeSet.id.

The activity variable stores a NumPy array of 365 float values from 0 to 19 (only whole numbers, only the type is float).

2024-06-28 20:26 UTC, Zaczero requested changes
If you don't want to work on JS and design, I can continue your work after this PR. Just let me know.

2024-06-28 20:26 UTC, Zaczero commented on app/controllers/user.py
> +    ).astype(datetime)
Let's store time in a variable to ensure consistency, I have also found a 1-off error (ACTIVITY_CHART_LENGTH=365 returned 366 days).

```py
today = utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
created_since = today - timedelta(days=ACTIVITY_CHART_LENGTH - 1)
```

```suggestion
    dates_range = np.arange(
        created_since,
        today + timedelta(days=1),
        timedelta(days=1),
        dtype=datetime,
    )
```

2024-06-28 20:26 UTC, Zaczero commented on app/queries/changeset_query.py
> +            )
You can move the date_trunc to a variable to make the query simpler:

```suggestion
            created_date = func.date_trunc('day', Changeset.created_at)
            stmt = (
                select(
                    created_date,
                    func.count(Changeset.id),
                )
                .where(Changeset.user_id == user_id)
                .where(created_date >= created_since)
                .group_by(created_date)
            )
```

2024-06-29 13:32 UTC, tomekrzymyszkiewicz commented on app/queries/changeset_query.py
> +            created_at_limit = utcnow() - timedelta(days=days)
Agree, I'll implement that

2024-06-29 13:39 UTC, merged